festcms/festcms/urls.py
import forms_builder.forms.urls

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forms/', include(forms_builder.forms.urls)),
    url(r'^', include('festflow.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

festcms/festflow/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from . import views

urlpatterns = [
    # Index Page
    url(r'^$', views.index, name='index'),

    # Home Page
    url(r'^home/$', views.home, name='home'),

    # Team Page
    url(r'^teams/$', views.teams, name='teams'),

    # About Page
    url(r'^about/$', views.about, name='about'),

    # Sponsors Page
    url(r'^sponsors/$', views.sponsors, name='sponsors'),

    # Contact Page
    url(r'^contact/$', views.contact, name='contact'),

    # Event Page
    url(r'^events/$', views.events, name='events'),

    # Event Groups List Page
    url(r'^events/groups$', views.event_group_list, name='event_group_list'),

    # Event Group Page
    url(r'^events/group/(?P<group_identifier>[a-z]*)/$',
        views.event_group, name='event_group'),

    # Keynotes Page
    url(r'^keynotes/$', views.keynotes, name='keynotes'),

    # Reach Us Page
    url(r'^reachus/$', views.reachus, name='reachus'),

    # FAQ Page
    url(r'^faq/$', views.faq, name='FAQ'),

    # Subscribe Page
    url(r'^subscribe/$', views.subscribe, name='subscribe'),

    # Event View Page
    url(r'^events/(?P<event_identifier>[a-z]*)/$',
        views.event_view, name='event_view'),

    # Keynote View Page
    url(r'^keynote/(?P<keynote_identifier>[a-z]*)/$',
        views.keynote_view, name='keynote_view'),

    # Event Register Page
    url(r'^register_event/(?P<event_identifier>[a-z]*)/$',
        views.register_event, name='register_event'),

    # Login Page
    url(r'^login/$', views.login_page, name='login_page'),

    # social login urls
    url('', include('social_django.urls')),

    # Form to complete profile
    url(r'^complete_profile/$',
        views.complete_profile, name='complete_profile'),

    # logout url
    url(r'^logout/$',
        logout, {'next_page': '/home'})
]

festcms/festflow/models.py
import hashlib

from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.urls import reverse, NoReverseMatch
from django.core.validators import RegexValidator, URLValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


lowercaseAlphabet = RegexValidator(
    r'^[a-z]*$', 'Only lower case alphabets are allowed.')


def validate_navbar_entry(url):
    domain = Site.objects.get_current().domain
    try:
        reverse(url)
    except NoReverseMatch:
        try:
            URLValidator()(url)
        except ValidationError:
            URLValidator()('https://%s%s' % (domain, url))
# Create your models here.


class EventGroup(models.Model):
    """Organize events into groups"""
    group_identifier = models.CharField(max_length=50, unique=True,
                                        validators=[lowercaseAlphabet])
    group_name = models.CharField(max_length=100)
    # event group logo
    logo = models.ImageField(upload_to='event_group_images/',
                             blank=True, null=True)

    def __str__(self):
        return self.group_identifier

    def get_absolute_url(self):
        return '/events/group/%s/' % self.group_identifier


class Event(models.Model):
    "Stores information about the events in the fest"

    # event id
    identifier = models.CharField(max_length=50, unique=True,
                                  validators=[lowercaseAlphabet])

    # event name
    name = models.CharField(max_length=255)

    # event description
    description = models.TextField()

    # event logo
    logo = models.ImageField(upload_to='event_images/',
                             blank=True, null=True)

    # event problem statement file
    problem_statement_file = models.FileField(upload_to='problem_statements/',
                                              blank=True, null=True)

    # event venue
    venue = models.CharField(max_length=255)
    venue_lat = models.DecimalField(max_digits=9, decimal_places=8,
                                    blank=True, null=True)
    venue_lon = models.DecimalField(max_digits=9, decimal_places=8,
                                    blank=True, null=True)

    # event date and time
    date_time = models.DateTimeField()

    # group
    group = models.ForeignKey('EventGroup', on_delete=models.SET_NULL,
                              null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/events/%s/' % self.identifier


class Keynote(models.Model):
    "Stores information about the keynote speech or talk in the fest"

    # keynote id
    identifier = models.CharField(max_length=50, unique=True,
                                  validators=[lowercaseAlphabet])

    # keynote name
    name = models.CharField(max_length=255)

    # keynote description
    description = models.TextField()

    # keynote image
    image = models.ImageField(upload_to='event_images/',
                              blank=True, null=True)

    # keynote venue
    venue = models.CharField(max_length=255)

    # keynote date and time
    date_time = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/keynote/%s/' % self.identifier


class Profile(models.Model):
    "Stores additional information about the user"

    # each profile is associated with a user
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # profile informations:
    institute_name = models.CharField(max_length=255)
    degree_name = models.CharField(max_length=255)
    major_subject_name = models.CharField(max_length=255)

    phone_number = models.CharField(max_length=15)

    # events registered for
    registered_events = models.ManyToManyField(Event)

    def __str__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return '/events/%s/' % self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    # create a dummy profile for superuser
    if created and instance.is_superuser:
        Profile.objects.create(user=instance)
        instance.profile.save()


class organizerMember(models.Model):
    """Stores information about the members of the organization
    that is conducting the fest"""

    name = models.CharField(max_length=100)

    position = models.CharField(max_length=100)

    rank = models.IntegerField(default=0)

    avatar_img = models.ImageField(upload_to='avatar_images/',
                                   blank=True, null=True)

    contactNumber = models.CharField(max_length=15)

    emailId = models.EmailField(blank=True, null=True)

    contactURL = models.URLField(blank=True, null=True)

    CLUB_CHOICES = (
        ('GLUG', 'GNU Linux Users\' Group'),
        ('MNTC', 'Maths And Tech Club'),
        ('SAE', 'SAE'),
    )
    club = models.CharField(
        max_length=5,
        choices=CLUB_CHOICES,
        default='GLUG',
    )

    def __str__(self):
        return self.name


class SponsorGroup(models.Model):
    """Organize events into groups"""
    group_identifier = models.CharField(max_length=50, unique=True,
                                        validators=[lowercaseAlphabet])
    group_name = models.CharField(max_length=100)
    # event group logo

    def __str__(self):
        return self.group_identifier


class Sponsor(models.Model):
    """Stores information about fest sponsors
    """
    name = models.CharField(max_length=100)

    logo = models.ImageField(upload_to='sponsor_logos/')

    rank = models.IntegerField(default=0)

    group = models.ForeignKey('SponsorGroup', on_delete=models.SET_NULL,
                              null=True, blank=True)

    def __str__(self):
        return self.name


class About(models.Model):
    """Stores about content as raw html
    """
    identifier = models.CharField(max_length=50, unique=True)
    content = models.TextField()

    def __str__(self):
        return self.identifier

    class Meta:
        verbose_name = "about"
        verbose_name_plural = "about"


class NewsLetter(models.Model):
    """Stores newsletters sent to subscribed users
    """
    identifier = models.CharField(max_length=50, unique=True)
    content = models.TextField()

    def __str__(self):
        return self.identifier


class Subscription(models.Model):
    """Stores the details of subscribed users
    """
    identifier = models.CharField(max_length=50, unique=True)
    contact_email = models.EmailField(unique=True)

    def save(self, *args, **kwargs):
        """On save, add unique identifier
        """
        hasher = hashlib.md5(self.contact_email.encode())
        self.identifier = hasher.hexdigest()
        return super(Subscription, self).save(*args, **kwargs)

    def __str__(self):
        return self.contact_email


class FAQ(models.Model):
    """Stores the frequently asked questions
    """
    identifier = models.CharField(max_length=50, unique=True)
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.identifier

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'


class NavbarEntry(models.Model):
    """Stores the navigation bar entries
    """
    url = models.CharField(default='#', max_length=100,
                           validators=[validate_navbar_entry])
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Navbar Entry'
        verbose_name_plural = 'Navbar Entries'

festcms/festflow/forms.py
from django.forms import ModelForm
from .models import *


class EditProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ['institute_name', 'degree_name',
                  'major_subject_name', 'phone_number']


class SubscriptionForm(ModelForm):

    class Meta:
        model = Subscription
        fields = ['contact_email']

festcms/festflow/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import render, redirect, Http404
from social_core.pipeline.utils import partial_load
from social_django.utils import load_strategy

from .forms import *
from .models import *
from .utils import *

# Create your views here.


def index(request):
    context = {}
    profiles_count = Profile.objects.count()
    all_events = Event.objects.all()

    context['profiles_count'] = profiles_count
    context['all_events'] = all_events

    return render(request, 'festflow/index.html', context)


def home(request):
    context = {}
    profiles_count = Profile.objects.count()
    all_events = Event.objects.all()

    context['profiles_count'] = profiles_count
    context['all_events'] = all_events

    return render(request, 'festflow/homePage.html', context)


def teams(request):
    context = {}
    all_members = organizerMember.objects.all().order_by('rank')
    context['members'] = all_members
    return render(request, 'festflow/teams.html', context)


def about(request):
    context = {}
    context['content'] = About.objects.last()
    return render(request, 'festflow/about.html', context)


def events(request):
    context = {}
    all_events = Event.objects.all()
    context['all_events'] = all_events
    return render(request, 'festflow/event.html', context)


def event_group_list(request):
    context = {}
    all_groups = EventGroup.objects.all()
    context['all_groups'] = all_groups
    return render(request, 'festflow/event_group_list.html', context)


def event_group(request, group_identifier):
    context = {}
    group = EventGroup.objects.get(group_identifier=group_identifier)
    group_events = Event.objects.filter(group=group)
    print(list(group_events))
    context['group_events'] = group_events
    return render(request, 'festflow/event_group.html', context)


def keynotes(request):
    context = {}
    all_events = Keynote.objects.all()
    context['all_keynotes'] = all_events
    return render(request, 'festflow/keynote.html', context)


def sponsors(request):
    context = {}
    all_groups = SponsorGroup.objects.all()
    sponsors = {}
    for group in all_groups:
        sponsor_list = Sponsor.objects.filter(group=group)
        sponsors[group] = sponsor_list
    print(sponsors)
    context['sponsors'] = sponsors
    return render(request, 'festflow/spons.html', context)


def contact(request):
    context = {}
    all_contacts = organizerMember.objects.all()
    context['all_contacts'] = all_contacts
    return render(request, 'festflow/contact.html', context)


def reachus(request):
    context = {}
    context["google_api_key"] = settings.GOOGLE_API_KEY
    return render(request, 'festflow/reachus.html', context)


def faq(request):
    context = {}
    context['faqs'] = FAQ.objects.all()
    return render(request, 'festflow/faq.html', context)


def login_page(request):
    context = {}
    profiles_count = Profile.objects.count()
    context['profiles_count'] = profiles_count
    return render(request, 'festflow/login_page.html', context)


def event_view(request, event_identifier):
    context = {}
    try:
        event = Event.objects.get(identifier=event_identifier)
    except ObjectDoesNotExist:
        raise Http404

    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user=request.user)
        context['user_profile'] = user_profile

    context['event'] = event

    return render(request, 'festflow/event_view.html', context)


def keynote_view(request, keynote_identifier):
    context = {}
    try:
        keynote = Keynote.objects.get(identifier=keynote_identifier)
    except ObjectDoesNotExist:
        raise Http404

    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user=request.user)
        context['user_profile'] = user_profile

    context['keynote'] = keynote

    return render(request, 'festflow/keynote_view.html', context)


@login_required
def register_event(request, event_identifier):
    try:
        event = Event.objects.get(identifier=event_identifier)
    except ObjectDoesNotExist:
        raise Http404

    user_profile = Profile.objects.get(user=request.user)
    user_profile.registered_events.add(event)
    user_profile.save()

    return redirect(event.get_absolute_url())


def complete_profile(request):
    strategy = load_strategy(request)
    partial = partial_load(strategy, request.session['partial_pipeline_token'])
    context = {}
    backend = partial.backend
    user_id = partial.kwargs['user'].id
    user_obj = User.objects.get(id=user_id)

    if request.method == 'POST':
        profile_form = EditProfileForm(request.POST)
        if profile_form.is_valid():
            new_profile = profile_form.save(commit=False)
            new_profile.user = user_obj
            new_profile.save()
            return redirect('/complete/%s' % backend)
    else:
        profile_form = EditProfileForm()

    context['user'] = user_obj
    context['backend'] = backend
    context['profile_form'] = profile_form
    return render(request, 'festflow/complete_profile.html', context)


def subscribe(request):
    context = {}

    if request.method == 'POST':
        form = SubscriptionForm(request.POST)
        to_addr = request.POST.get('contact_email', '')
        if Subscription.objects.filter(contact_email=to_addr).count():
            context['result'] = ('Your email: %s has already'
                                 ' been subscribed.' % to_addr)
        elif form.is_valid():
            form.save()
            send_subscription_success(
                from_addr=settings.DEFAULT_FROM_EMAIL,
                to_addr=to_addr,
                template='subscribed_email',)
            context['result'] = ('Your email: %s is successfully'
                                 ' subscribed.' % to_addr)
    else:
        form = SubscriptionForm
        context['subscription_form'] = form
        id = request.GET.get('unsubscribe', '')
        if len(id) != 0:
            context['unsubscribe'] = unsubscribe(id)

    return render(request, 'festflow/subscribe.html', context)

festcms/festflow/templates/festflow/about.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} Aavishkar 2018 - About {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href="{% static "css/about.css"%}"/>

{% endblock %}

{% block body_contents %}
    {% include "festflow/navBar.html" %}
    <div class="container">
        <header>
            <div class="row">
                <div class="col-md-8">
                    <h1>About Us</h1>
                    <p class="info">
                        {% if content %}
                        {{ content.content | safe }}
                        {% endif %}
                    </p>
                </div>
            </div>
        </header>
    </div>
{% endblock %}

festcms/festflow/templates/festflow/base.html
<!DOCTYPE html>
{% load static %}
{% load navbar %}
<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115495181-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-115495181-1');
    </script>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Aavishkar{% endblock %}</title>
    <link rel="shortcut icon" href="{% static "images/Aavishkar Logo Final (RGB).png" %}">
    <link rel="stylesheet" href="{% static "vendor/css/animate.css"%}"/>
    <link rel="stylesheet" href="{% static "vendor/css/bootstrap-theme.min.css"%}"/>
    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css"%}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css"%}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css"%}"/>
    <style >
        .hameid-loader-overlay {
            width: 100%;
            height: 100%;
            background: url('{% static "images/1-dancing.gif"%}') center no-repeat #FFF;
            z-index: 99999;
            position: fixed;
        }
    </style>
    <script src="{% static "vendor/js/jquery-3.3.1.min.js"%}"></script>
    {% block extra_head %}{% endblock %}
</head>

<body>
    <!-- PRELOADER -->
    <div class="hameid-loader-overlay">
    </div>
    
    {% block body_contents %}{% endblock %}
    <div class="footer">
        {# <span class="fa fa-twitter social"></span> #}
        <a href="https://www.facebook.com/aavishkar.nitd/" target="_blank"><span class="fa fa-facebook"></span></a>
        <a href="https://www.instagram.com/aavishkar_nitd/" target="_blank"><span class="fa fa-instagram"></span></a>
        <a href="https://www.youtube.com/channel/UCl42je3Zr5zTCpsHIj7xkbg" target="_blank"><span class="fa fa-youtube"></span></a>
    </div>
    <script>
        $(document).ready(function(){
            console.log("READY");
            $('.hameid-loader-overlay').delay(1000).fadeOut();
            $('#main').delay(5000).fadeIn();
        });
    </script>
    <!-- <script src="{% static "js/main.js"%}"></script> -->
    <noscript>
        <style>.hameid-loader-overlay { display: none; } </style>
    </noscript>

    <script src="{% static "vendor/js/bootstrap.min.js"%}"></script>
    {% block extrajs %}{% endblock %}
</body>

</html>

festcms/festflow/templates/festflow/complete_profile.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} Complete Profile {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/other.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h1 id='link'>Complete Profile</h1>
        <div class="dash"></div>
        <br />
        <br />

        {% if user.is_authenticated %}
        <!--User is logged in-->
        <h3 id='link'>Profile Info</h3>
        <div class="subdash"></div>
        <br />
        <br />
        <p>Welcome <b>{{ user.first_name }}</b>!</p>

        <table class="table ">
            <tbody>
                <tr>
                    <td>First Name :</td>
                    <td><strong> {{ user.first_name }}</strong></td>
                </tr>
                <tr>
                    <td>Last Name :</td>
                    <td><strong> {{ user.last_name }}</strong></td>
                </tr>
                <tr>
                    <td>Email :</td>
                    <td><strong> {{ user.email }}</strong></td>
                </tr>
            </tbody>
        </table>
        {% endif %}

        <h3 id='link'><strong>Please complete your profile to continue</strong></h3>
        <div class="subdash"></div>
        <br />
        <br />
        {% if profile_form %}
        <form action="." method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_institute_name">Institute Name:</label>
                <input class="form-control" id="id_institute_name" maxlength="255" name="institute_name" type="text" required />
            </div>

            <div class="form-group">
                <label for="id_degree_name">Degree:</label>
                <input class="form-control" id="id_degree_name" maxlength="255" name="degree_name" type="text" placeholder="eg: B.Tech"required />
            </div>

            <div class="form-group">
                <label for="id_major_subject_name">Major:</label>
                <input class="form-control" id="id_major_subject_name" maxlength="255" name="major_subject_name" type="text" placeholder="eg: Information Technology "required />
            </div>

            <div class="form-group">
                <label for="id_phone_number">Phone Number:</label>
                <input class="form-control" id="id_phone_number" maxlength="15" name="phone_number" type="text" required />
            </div>

            <button type="submit" class="btn btn-primary btn-block">Submit</button>

        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

festcms/festflow/templates/festflow/contact.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} CONTACT {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/other.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h1 id='link'>  Contact Us </h1>
        <div class="dash"></div>
        <br />
        <br />
        <br />
        <div class='row'>

            {% for contact in all_contacts %}
            <div class='col-lg-3'>
                <a href="{{contact.contactURL}}" target="_blank">
                    {% if contact.avatar_img %}
                    <img src="{{contact.avatar_img.url}}" width='100%' alt='{{ contact.name }}' class='img-responsive img-circle' />
                    {% endif %}
                </a>
                <div class="subdash"></div>
                <table class="table ">
                    <tbody>
                        <tr>
                            <td class='contact'><strong> {{ contact.name }}</strong></td>
                        </tr>
                        <tr>
                            <a href="tel:{{contact.contactNumber}}">
                                <td class='contact'><strong> {{contact.contactNumber}}</strong></td>
                            </a>
                        </tr>
                        <tr>
                            <a href="mailto:{{contact.emailId}}">
                                <td class='contact'><strong> {{contact.emailId}}</strong></td>
                            </a>
                        </tr>
                    </tbody>
                </table>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

festcms/festflow/templates/festflow/event_group (backup).html
{% extends "festflow/base.html" %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "css/event_group.css"%}" />
{% endblock %}

{% block extrajs %}
  <script src="{% static "js/event_group.js" %}"></script>
{% endblock %}

{% block body_contents %}
{% include "festflow/navBar.html" %}
  <div id="main">
      <div class="container">
        <div class="carousel">
          {{group_events.count}}
          {% for event in group_events %}
            <a href="{{ event.get_absolute_url }}">
              <div class="item" style="transform: rotateY({% widthratio forloop.counter0 1 120 %}deg) translateZ(250px);background: url('{{event.logo.url}}'); background-size: cover;"></div>
            </a>
          {% endfor %}
        </div>
      </div>
      <div class="next">Next</div>
      <div class="prev">Prev</div>
  </div>
{% endblock %}


{% comment %}

{% extends "festflow/base.html" %}
{% load static %}

{% block title %} EVENTS {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/other.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h1 id='link'>Events</h1>
        <div class="dash"></div>
        <br />
        <br />
        <br />
        <div class='row'>
            {% for event in group_events %}
            <div class='col-lg-4'>
                <a href="{{ event.get_absolute_url }}">
                    {% if event.logo %}
                    <img src="{{ event.logo.url }}" width='100%' alt= "{{ event.name }}" class='img-responsive' />
                    {% endif %}
                    <div class='event-text'>
                        <div class="subdash"></div>
                        <p>{{ event.name }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}
{% endcomment %}

festcms/festflow/templates/festflow/event_group.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} Aavishkar 2018 - {{ group_events.0.group.group_name }} {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href="{% static "css/event.css"%}"/>

{% endblock %}

{% block body_contents %}
{% include "festflow/navBar.html" %}
<div class="container">
    <div class="jumbotron">
        <h1 id='link'>{{ group_events.0.group.group_name }}</h1>
        <div class="dash"></div>
        <br />
        <br />
        <br />
        {% for event in group_events %}
        {% if forloop.counter0|divisibleby:3 %}<div class='row'>{% endif %}
            <div class='col-lg-4'>
                <a href="{{ event.get_absolute_url }}">
                    {% if event.logo %}
                    <img src="{{ event.logo.url }}" width='100%' alt= "{{ event.name }}" class='img-responsive' />
                    {% endif %}
                    <div class='event-text'>
                        <div class="subdash"></div>
                        <p>{{ event.name }}</p>
                    </div>
                </a>
            </div>
        {% if forloop.counter|divisibleby:3 or forloop.last %}</div>{% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

festcms/festflow/templates/festflow/event_group_list.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %}Aavishkar 2018 - Events{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "css/events_group_list.css" %}"/>
{% endblock %}

{% block extrajs %}
{% endblock %}

{% block body_contents %}  
    {% include "festflow/navBar.html" %}
    <div class="events_group">
        <div style="top:7em;width:100%;height:100%;text-align: center;">
            <h1>EVENTS</h1><br>
            {% for group in all_groups %}
              <a href="{{group.get_absolute_url}}">
                {% if group.logo %} 
                  <div class="blog-card">
                    <img class="img-responsive" src="{{group.logo.url}}">
                    <div class="title-content">
                      <h3 style="color: #000;">{{ group.group_name }}</h3>
                      <hr/>
                    </div>
                  </div>
                {% endif %}
              </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% comment %}

{% extends "festflow/base.html" %}
{% load static %}

{% block title %} EVENTS {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/other.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h1 id='link'>Events</h1>
        <div class="dash"></div>
        <br />
        <br />
        <br />
        <div class='row'>
            {% for group in all_groups %}
            <div class='col-lg-4'>
                <a href="{{ group.get_absolute_url }}">
                    {% if group.logo %}
                    <img src="{{ group.logo.url }}" width='100%' alt= "{{ group.name }}" class='img-responsive' />
                    {% endif %}
                    <div class='group-text'>
                        <div class="subdash"></div>
                        <p>{{ group.group_name }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}
{% endcomment %}

festcms/festflow/templates/festflow/newsletter.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} NEWSLETTER {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/other.css" %}'/>

{% endblock %}
{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h1 id='link'>Newsletter</h1>
        <div class="dash"></div>
        <br />
        <br />
        <div>
            {{ newsletter }}
        </div>
        <a href="{{url}}" class="btn btn-primary" role="button">Unsubscribe</a>
    </div>
</div>

{% endblock %}